### PR TITLE
Properly migrate orphan import-only files

### LINKED ISSUE #160: Properly support changing paths through an import-only file
Right now, the module migrator always includes a `@use` and/or `@forward` rule with the exact URL of each `@import` rule, even if that URL has an import-only file that doesn't forward the regular file.

e.g.

```
<==> entrypoint.scss
@import "old";

a { b: $lib-variable; }

<==> _old.scss
@error "Use 'new'";

<==> _old.import.scss
@forward "new" as lib-*;

<==> _new.scss
$variable: blue;
```

Right now, the entrypoint would be migrated to:
```
@use "old";
@use "new";

a { b: new.$variable }
```

While a `@use` rule with a new URL is added, and the namespacing is correct, the `@import "old";` is also migrated to a `@use`, which is wrong, since the import-only file for `old` old forwards `new`.

### PR DESCRIPTION
**Pull request by jathak**
Fixes #160.

### CODE REVIEW

File: lib/src/migrators/module.dart [hunk 1]
```diff
@@ -746,7 +745,11 @@ class _ModuleMigrationVisitor extends MigrationVisitor {
     var imports =
         partitionOnType<Import, StaticImport, DynamicImport>(node.imports);
     var staticImports = imports.item1;
-    var dynamicImports = imports.item2;
+    var dynamicImports = imports.item2.where((import) =>
+        !references.orphanImportOnlyFiles.contains(importCache
+            .canonicalize(Uri.parse(import.url),
+                baseImporter: importer, forImport: true)
+            ?.item2));
```
Comment (nex3) [inline lib/src/migrators/module.dart:752]: Nit: I think this would be easier to read if you split it into separate statements.

```suggestion
    var dynamicImports = imports.item2.where((import) {
      var url = importCache.canonicalize(
              Uri.parse(import.url), baseImporter: importer, forImport: true)
          ?.item2;
      return !references.orphanImportOnlyFiles.contains(url);
    });
```

**Review by nex3 — APPROVED** [review]
