### PR TITLE
Warn instead of crashing for bad URLs

### LINKED ISSUE #57: Crashes on a URL that can't be loaded
When the migrator encounters a URL that can't be loaded in `--migrate-deps` mode, it crashes:

```shellsession
$ echo "@import 'asdf';" > test.scss
$ dart bin/sass_migrator.dart division -d test.scss
Unhandled exception:
Invalid argument (uri): Value must be a String or a Uri: null
#0      _parseUri (package:path/src/context.dart:1065:3)
#1      Context.fromUri (package:path/src/context.dart:986:44)
#2      fromUri (package:path/path.dart:410:32)
#3      FilesystemImporter.load (package:sass/src/importer/filesystem.dart:30:16)
#4      parseStylesheet (package:sass_migrator/src/utils.dart:30:36)
#5      MigrationVisitor.visitDependency (package:sass_migrator/src/migration_visitor.dart:71:22)
#6      MigrationVisitor.visitImportRule (package:sass_migrator/src/migration_visitor.dart:99:11)
#7      ImportRule.accept (package:sass/src/ast/sass/statement/import_rule.dart:21:55)
#8      RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:215:13)
#9      RecursiveStatementVisitor.visitStylesheet (package:sass/src/visitor/recursive_statement.dart:133:41)
#10     MigrationVisitor.visitStylesheet (package:sass_migrator/src/migration_visitor.dart:60:11)
#11     MigrationVisitor.run (package:sass_migrator/src/migration_visitor.dart:46:5)
#12     DivisionMigrator.migrateFile (package:sass_migrator/src/migrators/division.dart:38:12)
#13     Migrator.run (package:sass_migrator/src/migrator.dart:48:22)
#14     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#15     MigratorRunner.execute (package:sass_migrator/runner.dart:45:26)
<asynchronous suspension>
#16     main (file:///home/nweiz/sass/migrator/bin/sass_migrator.dart:16:20)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

### LINKED ISSUE #59: Crashes on input parse errors
When the migrator encounters a parse error in an input file, it crashes:

```shellsession
$ echo 'a {' > test.scss
$ dart bin/sass_migrator.dart division test.scss                                                
Unhandled exception:
Error: expected "}".
  ,
1 | a {
  |    ^
  '
  test.scss 1:4  root stylesheet
#0      Parser.wrapSpanFormatException (package:sass/src/parse/parser.dart:663:7)
#1      StylesheetParser.parse (package:sass/src/parse/stylesheet.dart:93:12)
#2      new Stylesheet.parseScss (package:sass/src/ast/sass/statement/stylesheet.dart:61:54)
#3      new Stylesheet.parse (package:sass/src/ast/sass/statement/stylesheet.dart:39:27)
#4      parseStylesheet (package:sass_migrator/src/utils.dart:31:21)
#5      MigrationVisitor.run (package:sass_migrator/src/migration_visitor.dart:46:21)
#6      DivisionMigrator.migrateFile (package:sass_migrator/src/migrators/division.dart:38:12)
#7      Migrator.run (package:sass_migrator/src/migrator.dart:48:22)
#8      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#9      MigratorRunner.execute (package:sass_migrator/src/runner.dart:51:26)
<asynchronous suspension>
#10     main (file:///home/nweiz/sass/migrator/bin/sass_migrator.dart:16:20)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

### PR DESCRIPTION
**Pull request by jathak**
Fixes #57. Fixes #59.

The migrator will now print a warning for any URL that doesn't exist (both entrypoints and dependencies).

### CODE REVIEW

File: lib/src/utils.dart [hunk 1]
```diff
@@ -58,9 +67,13 @@ Patch patchDelete(FileSpan span, {int start = 0, int end}) {
       span.file.span(span.start.offset + start, span.start.offset + end), "");
 }
 
-/// Emits a warning with [message] and [context];
-void emitWarning(String message, FileSpan context) {
-  print(context.message("WARNING - $message"));
+/// Emits a warning with [message] and optionally [context];
+void emitWarning(String message, {FileSpan context}) {
```
Comment (nex3) [inline lib/src/utils.dart]: This is the sort of API where I'd lean towards an optional rather than a named parameter. You almost always want to pass a span, it's unlikely that you'll need other optional parameters later, and it's a private API so if you do you can change it to a named parameter then without breaking anything.

**Comment by jathak** [comment]
Okay, I changed the default to combine all warnings into one (when `--verbose` is passed, this combined warning will still list all of the missing dependencies, but in a shorter form then separate warnings would be).

The module migrator now throws a MigrationException, which the runner now catches and prints.

File: lib/src/migrator.dart [hunk 2]
```diff
@@ -45,7 +48,12 @@ abstract class Migrator extends Command<Map<Uri, String>> {
   Map<Uri, String> run() {
     var allMigrated = Map<Uri, String>();
     for (var entrypoint in argResults.rest) {
-      var migrated = migrateFile(canonicalize(Uri.parse(entrypoint)));
+      var canonicalUrl = canonicalize(Uri.parse(entrypoint));
+      if (canonicalUrl == null) {
+        throw MigrationException(
+            "Error: Could not find Sass file at '$entrypoint'.");
```
Comment (nex3) [inline lib/src/migrator.dart]: Should entrypoint go through `p.prettyUri()`?

File: lib/src/migrator.dart [hunk 3]
```diff
@@ -45,7 +48,12 @@ abstract class Migrator extends Command<Map<Uri, String>> {
...
+      }
```
Comment (nex3) [inline lib/src/migrator.dart]: Consider splitting up these code blocks with newlines to make them easier to visually distinguish.

File: lib/src/migrator.dart [hunk 4]
```diff
@@ -55,6 +63,16 @@ abstract class Migrator extends Command<Map<Uri, String>> {
...
+    if (missingDependencies.isNotEmpty) {
+      var count = missingDependencies.length;
+      emitWarning(
+          "$count dependenc${count == 1 ? 'y' : 'ies'} could not be found.");
+      if (globalResults['verbose'] as bool) {
+        for (var warning in missingDependencies) {
+          print('  $warning');
+        }
+      }
+    }
```
Comment (nex3) [inline lib/src/migrator.dart]: Also consider abstracting this condition into a separate method to make this method shorter.

File: lib/src/migrator.dart [hunk 5]
```diff
@@ -55,6 +63,16 @@ abstract class Migrator extends Command<Map<Uri, String>> {
         allMigrated[file] = migrated[file];
       }
     }
+    if (missingDependencies.isNotEmpty) {
+      var count = missingDependencies.length;
+      emitWarning(
+          "$count dependenc${count == 1 ? 'y' : 'ies'} could not be found.");
```
Comment (nex3) [inline lib/src/migrator.dart]: It would be good to list the URLs here. It's a little more verbose for users who genuinely don't care, but it'll serve as a sanity check that it's the sort of URLs they're expecting.

File: test/migrators/division/bad_paths_verbose.hrx [hunk 6]
```diff
@@ -0,0 +1,12 @@
+<==> arguments
+--migrate-deps --verbose
+
+<==> input/entrypoint.scss
+@import "does_not_exist";
+@import "does_not_exist2";
+
+<==> log.txt
+WARNING - 2 dependencies could not be found.
+  does_not_exist @entrypoint.scss:1
```
Comment (nex3) [inline test/migrators/division/bad_paths_verbose.hrx]: In verbose mode, I think the messages should include the full source span decoration.

File: lib/src/migrator.dart (hunk 2 above)
Comment (jathak) [reply lib/src/migrator.dart]: Since `entrypoint` comes directly from the arguments passed to the executable, I figured it made more sense to just error with the exact text entered by the user.

File: lib/src/migration_visitor.dart [hunk 7]
```diff
@@ -34,6 +35,11 @@ abstract class MigrationVisitor extends RecursiveAstVisitor {
   /// True if dependencies should be migrated as well.
   final bool migrateDependencies;
 
+  /// Map of missing dependency URLs to the spans that import/use them.
+  UnmodifiableMapView<Uri, FileSpan> get missingDependencies =>
```
Comment (nex3) [inline lib/src/migration_visitor.dart]:
```suggestion
  Map<Uri, FileSpan> get missingDependencies =>
```

File: lib/src/migration_visitor.dart [hunk 8]
```diff
@@ -67,9 +73,14 @@ abstract class MigrationVisitor extends RecursiveAstVisitor {
...
-  void visitDependency(Uri dependency, Uri source) {
-    var stylesheet = parseStylesheet(source.resolveUri(dependency));
-    visitStylesheet(stylesheet);
+  void visitDependency(Uri dependency, Uri source, [FileSpan context]) {
+    var url = source.resolveUri(dependency);
+    var stylesheet = parseStylesheet(url);
+    if (stylesheet != null) {
+      visitStylesheet(stylesheet);
+    } else {
+      _missingDependencies[url] = context;
```
Comment (nex3) [inline lib/src/migration_visitor.dart]:
```suggestion
      _missingDependencies.putIfAbsent(url, () => context);
```

This is minor, but I think it's more likely that an earlier import is more relevant to the user.

File: lib/src/migrator.dart (hunk 2 above)
Comment (nex3) [reply lib/src/migrator.dart]: SGTM

File: lib/src/migrator.dart [hunk 9]
```diff
@@ -26,6 +28,9 @@ abstract class Migrator extends Command<Map<Uri, String>> {
   /// If true, dependencies will be migrated in addition to the entrypoints.
   bool get migrateDependencies => globalResults['migrate-deps'] as bool;
 
+  /// Map of missing dependency URLs to the spans that import/use them.
+  final missingDependencies = <Uri, FileSpan>{};
```
Comment (nex3) [inline lib/src/migrator.dart]: Document how subclasses are intended to interact with this.

File: lib/src/migrators/division.dart [hunk 10]
```diff
@@ -36,9 +36,13 @@ More info: https://sass-lang.com/d/slash-div""";
...
 
   @override
-  Map<Uri, String> migrateFile(Uri entrypoint) =>
-      _DivisionMigrationVisitor(this.isPessimistic, migrateDependencies)
-          .run(entrypoint);
+  Map<Uri, String> migrateFile(Uri entrypoint) {
+    var visitor =
+        _DivisionMigrationVisitor(this.isPessimistic, migrateDependencies);
+    var result = visitor.run(entrypoint);
+    missingDependencies.addAll(visitor.missingDependencies);
```
Comment (nex3) [inline lib/src/migrators/division.dart]: Bleh, it sucks that each subclass has to do this manually rather than just having "warn for missing dependencies" be the automatic default behavior. It's not something that needs to happen in this PR, but it's worth thinking about how you could make this more automatic.

Comment (jathak) [reply lib/src/migrators/division.dart]: Yeah, that's why I originally passed in the list for the visitor to add to, but this is probably cleaner than that, particularly right now when there's only one migrator that actually uses `missingDependencies`. Created #64 for this.
