### PR TITLE
`--remove-prefix` fixes for private members

### LINKED ISSUE #169: Private members unnecessarily hidden by @forward rules in import-only files

### PR DESCRIPTION
**Pull request by jathak**
Fixes #169.

Unnecessary hide clauses will no longer be added to import-only files.
Prefixes can now also be removed from private members.

### CODE REVIEW

File: lib/src/migrators/module.dart [hunk 1]
```diff
@@ -245,9 +245,11 @@ class _ModuleMigrationVisitor extends MigrationVisitor {
     var hiddenByUrl = <Uri, Set<MemberDeclaration>>{};
     for (var declaration in references.globalDeclarations) {
       var private = declaration.name.startsWith('-');
+
       // Whether this member will be exposed by the regular entrypoint.
-      var visibleAtEntrypoint = declaration.sourceUrl == entrypoint ||
-          (_shouldForward(declaration.name) && !private);
+      var visibleAtEntrypoint = (declaration.sourceUrl == entrypoint ||
+              _shouldForward(declaration.name)) &&
+          !private;
```
Comment (nex3) [inline lib/src/migrators/module.dart:252]:
```suggestion
      var visibleAtEntrypoint = !private &&
          (declaration.sourceUrl == entrypoint || _shouldForward(declaration.name));
```

Nit: I think this would read a bit better (and possibly be a bit more efficient).

File: lib/src/migrators/module.dart [hunk 2]
```diff
@@ -1167,8 +1173,11 @@ class _ModuleMigrationVisitor extends MigrationVisitor {
   ///
   /// Otherwise, returns [name] unaltered.
   String _unprefix(String name) {
-    var prefix = _prefixFor(name);
-    return prefix == null ? name : name.substring(prefix.length);
+    var unprivateName = name.startsWith('-') ? name.substring(1) : name;
+    var prefix = _prefixFor(unprivateName);
+    if (prefix == null) return name;
+    return (name == unprivateName ? '' : '-') +
```
Comment (nex3) [inline lib/src/migrators/module.dart:1179]: Rather than `name == unprivateName` here, consider adding an `isPrivate` variable above.

**Review by nex3 — APPROVED** [review]
